server:
  port: 8080

stats-server:
  url: http://localhost:9090

spring:
  datasource:
    url: jdbc:postgresql://ewm-db:5432/ewm_main_db
    username: ewm_user
    password: ewm_password
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
    ru.practicum.explorewithme.main: DEBUG